# Generated by Django 4.2.2 on 2023-06-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_estudiante_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Nota Estudiante',
                'verbose_name_plural': 'Notas de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='NotaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante', verbose_name='Estudiante')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota.nota', verbose_name='Examen')),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='estudiantes',
            field=models.ManyToManyField(through='nota.NotaDetalle', to='usuario.estudiante', verbose_name='Lista de estudiantes'),
        ),
        migrations.AddField(
            model_name='nota',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota.examen', verbose_name='Nombre'),
        ),
    ]
