# Generated by Django 4.2.2 on 2023-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
