# Generated by Django 4.2.2 on 2023-06-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horario', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEstudianteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('asis_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistenciaestudiante', verbose_name='Asistencias')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='asistencia_estudiante',
            field=models.ManyToManyField(through='asistencia.AsistenciaEstudianteDetalle', to='usuario.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.horario', verbose_name='Horario'),
        ),
        migrations.CreateModel(
            name='AsistenciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha y Hora')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.docente', verbose_name='Docente')),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.horario', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
