# Generated by Django 4.2.2 on 2023-06-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_asistenciaestudiante_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha y Hora'),
        ),
    ]
