# Generated by Django 4.2.2 on 2023-06-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistenciaestudiante_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciadocente',
            options={'verbose_name': 'Asistencia Docente', 'verbose_name_plural': 'Asistencias de Docentes'},
        ),
        migrations.AlterModelOptions(
            name='asistenciaestudiante',
            options={'verbose_name': 'Asistencia Estudiante', 'verbose_name_plural': 'Asistencia de Estudiantes'},
        ),
        migrations.AlterField(
            model_name='asistenciadocente',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
