# Generated by Django 4.2.2 on 2023-06-10 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=8, null=True, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('direccion_residencia', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número celular')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('nivel_educativo', models.CharField(choices=[('P', 'Primaria'), ('S', 'Secundaria'), ('SC', 'Secundaria culminada')], max_length=50, verbose_name='Nivel Educativo')),
                ('escuela_procedencia', models.CharField(max_length=200, verbose_name='Escuela de Procedencia')),
                ('telefono_emergencia', models.CharField(max_length=20, verbose_name='Telefono de Emergencia')),
                ('carrera_interes', models.CharField(max_length=100, verbose_name='Carrera de Interes')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_docente', models.CharField(max_length=8, null=True, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('direccion_residencia', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Numero celular')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
