# Generated by Django 4.2.2 on 2023-06-12 21:10

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    if not User.objects.filter(is_superuser=True).exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@gmail.com',
            password='admin'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_estudiante_apellido'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
