# Generated by Django 4.2.2 on 2023-06-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('MI', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=2, null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.curso', verbose_name='Curso')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.docente', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horario',
            },
        ),
    ]
